### ISSUE TITLE
failed to connect to : context deadline exceeded

### ISSUE THREAD

**Issue by gothburz** [target/strelka#205]
**Describe the bug**
Hey all I'm following the Quickstart steps in order to test this project but I'm running into `failed to connect to : context deadline exceeded` after starting the cluster and building/running the `strelka-fileshot` binary. Is there an extra step I'm missing? Looks like a great project and thanks in advance!

**Steps to reproduce**

1: Build and Start Strelka Cluster (Docker)
```
# Terminal 1
$ docker-compose -f build/docker-compose.yaml up
```
2. Build [Strelka-Fileshot](https://github.com/target/strelka/blob/master/docs/README.md#strelka-fileshot) (File Submitter)
```
# Terminal 2
$ go build github.com/target/strelka/src/go/cmd/strelka-fileshot
```
3. Add File Paths / Patterns to be Scanned to a [fileshot.yaml] file
```
files:
    patterns:
      - '/tmp/*'
```
4. Error
```
./strelka-fileshot -c fileshot.yaml
2022/05/05 08:56:46 failed to connect to : context deadline exceeded
```
**Expected behavior**
 Expect the scanner to scan and output results to ./strelka.log

**Release**
 - 0.22.04.26 & 0.21.11.29

**Additional context**
Tested on macOS Monterey & Ubuntu 22.04
Tested with both fileshot binary and fileshot container.

**Comment by phutelmyer** [comment]
Hi @gothburz, thanks for reporting this issue. That issue usually arises if the Strelka frontend containers are not running or the config does not have the address of the Strelka frontend address + port.

I just went ahead and built fileshot as displayed above and tested against `0.22.04.26` with no errors.

Do you mind sharing the config you're using with fileshot and a sample of the containers running?

Fileshot.yaml example
```
client: 'go-fileshot-testing'
conn:
  server: 'localhost:57314'
  timeout:
    dial: 5s
    file: 5m
throughput:
  concurrency: 8
  chunk: 98304
  delay: 1s
files:
  patterns:
     - './samples/scan_pe/*'
  delete: false
  gatekeeper: false
response:
  log: './test.log'
```

Containers
```
strelka_backend_1      | 2022-05-15 20:57:26 - [INFO] root [strelka-backend.main]: using backend configuration /etc/strelka/backend.yaml
strelka_backend_1      | 2022-05-15 20:57:26 - [DEBUG] root [strelka-backend.main]: verified coordinator is up
strelka_backend_1      | 2022-05-15 20:57:26 - [INFO] root [strelka-backend.work]: starting up
strelka_backend_1      | OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
```
