### ISSUE TITLE
Add Additional ScanHeader/ScanFooter Data Encodings

### ISSUE THREAD

**Issue by ryanohoro** [target/strelka#279]
**Is your feature request related to a problem? Please describe.**

Currently both ScanHeader and ScanFooter dump raw data into the events from files. This makes readability a challenge in event logs.

```
�PNG   IHDR��a pHYs��
```

**Describe the solution you'd like**

I propose adding additional fields for alternate encodings, which would be configurable, while retaining backward compatibility.

```yaml
  'ScanHeader':
    - positive:
        flavors:
          - '*'
      priority: 5
      options:
        length: 50
        encodings:
          - old
          - raw
          - backslash
          - hex
```

```
header.header: �PNG   IHDR��a pHYs��
header.raw: �PNG   IHDR��a pHYs��
header.backslash: \x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x04\xd4\x00\x00\x03{\x08\x00\x00\x00\x00\xa8\xce\x98\xe0\x00\x00\x00\tpHYs\x00\x00\x0b6\x00\x00\x0b6\x01
header.hex: 89504e470d0a1a0a0000000d49484452000004d40000037b0800000000a8ce98e0000000097048597300000b3600000b3601
```

**Describe alternatives you've considered**

**Additional context**
